### PR TITLE
Fix: various

### LINKED ISSUE #6: Lint
```
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:77:30: Trailing spaces not allowed.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:116:1: Expected indentation of 10 spaces but found 12.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:117:14: '+' should be placed at the end of the line.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:122:1: Expected indentation of 10 spaces but found 8.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:123:1: Expected indentation of 10 spaces but found 8.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:130:29: Trailing spaces not allowed.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:199:61: Trailing spaces not allowed.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:258:27: Trailing spaces not allowed.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:338:57: 'Errors' is not defined.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/index.js:364:11: 'results' is assigned a value but never used.
  /Users/da/git/misc/ilp-plugin-outgoing-settle/src/account.js:36:40: 'account' is not defined.
```

### PR DESCRIPTION
**Pull request by sharafian**
Closes #6 #7 #8

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -307,22 +311,17 @@ class PluginOutgoingSettle extends PluginMiniAccounts {
...
-
     debug('submitting settlement tx. account=', account.getAccount(),
       'xrp=' + account.getXrpAddressAndTag())
-    await this._api.submit(signed.signedTransaction)
 
-    await result
+    if (tag) paymentParams.destination.tag = Number(tag)
+    const { resultCode, resultMessage } = await this._txSubmitter('preparePayment', paymentParams)
+
+    if (resultCode !== 'tesSUCCESS') {
```
Comment (dappelt) [inline index.js]: After this PR is [merged](https://github.com/interledgerjs/ilp-plugin-xrp-paychan-shared/pull/10), the tx submitter will validate the result code.

Comment (dappelt) [reply index.js]: So you don't need to check `resultCode` here.
